# Generated by Django 5.1.2 on 2024-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_producttype_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='is_headoffice',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='title_np',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_np',
            field=models.CharField(default='Default Address', max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='landline',
            field=models.CharField(default='977', max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='landline1',
            field=models.CharField(default='977', max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_np',
            field=models.CharField(default='Site Name', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='office_type',
            field=models.CharField(choices=[('head_office', 'Head Office'), ('branch_office', 'Branch Office'), ('collection_center', 'Collection Center')], default='branch_office', max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone1',
            field=models.CharField(default='977', max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='name_np',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_np',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(default='Site Name', max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
