# Generated by Django 5.1.2 on 2024-11-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setting_goal_setting_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_type',
            name='order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
