# Generated by Django 5.1.2 on 2024-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productdetails_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrate',
            name='name',
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
