# Generated by Django 5.1.2 on 2024-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_interestrate_name_alter_interestrate_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestrate',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
