# Generated by Django 5.1.2 on 2024-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_interestrate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interestrate',
            name='name',
            field=models.CharField(default='Interest Rate', max_length=150),
        ),
    ]
