# Generated by Django 5.1.2 on 2024-11-21 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_setting_image_alter_interestrate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.TextField(max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='withdrawal_policy',
            field=models.TextField(max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
