# Generated by Django 5.1.2 on 2024-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_financialreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='is_renewable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='term_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
