# Generated by Django 5.1.2 on 2024-11-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_productdetails_is_renewable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='minimum_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
