# Generated by Django 5.1.2 on 2024-11-21 09:58

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_productdetails_minimum_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_message_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='file',
            field=models.FileField(null=True, upload_to='financial_reports/'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='image',
            field=models.ImageField(null=True, upload_to='financial_reports/'),
        ),
        migrations.AlterField(
            model_name='financialreporttype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='description',
            field=models.TextField(default='Popup Description', null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(default='Popup Title', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about',
            field=models.TextField(default='Default About', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(default='Default Address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='landline',
            field=models.CharField(default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='landline1',
            field=models.CharField(default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mission',
            field=models.TextField(default='Default Mission', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone1',
            field=models.CharField(default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='vision',
            field=models.TextField(default='Default Vision', null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(null=True, upload_to='social_icons/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='session',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team_type',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
