# Generated by Django 5.1.2 on 2024-11-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_team_is_message_featured_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='message_order_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
