# Generated by Django 5.1.2 on 2024-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_slider_description_alter_slider_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='popup',
            name='display_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='display_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='description', max_length=5000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
    ]
