# Generated by Django 5.1.2 on 2024-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_download_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.IntegerField()),
                ('staffs', models.IntegerField()),
                ('branches', models.IntegerField()),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
            ],
        ),
    ]
