# Generated by Django 5.1.2 on 2024-11-29 02:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link_button_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='loans',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='savings',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='shares',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='download',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='download',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='financial_reports/'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='financial_reports/'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='title_np',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='financialreporttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='description',
            field=models.TextField(blank=True, default='Popup Description', null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, default='Default Address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address_np',
            field=models.CharField(blank=True, default='Default Address', max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='landline',
            field=models.CharField(blank=True, default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='landline1',
            field=models.CharField(blank=True, default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name_np',
            field=models.CharField(blank=True, default='Site Name', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone1',
            field=models.CharField(blank=True, default='977', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slogan',
            field=models.CharField(blank=True, default='Default Slogan', max_length=350),
        ),
        migrations.AlterField(
            model_name='setting',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_np',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name_np',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
