# Generated by Django 5.1.2 on 2024-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_slider_link_button_text_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.ManyToManyField(to='core.team_type'),
        ),
    ]
