# Generated by Django 5.1.2 on 2024-11-29 03:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_team_team_type_team_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='products/'),
            preserve_default=False,
        ),
    ]
