# Generated by Django 5.1.2 on 2024-11-29 15:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_description_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='goal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='objective',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slogan',
            field=models.CharField(blank=True, default='Default Slogan', max_length=550),
        ),
        migrations.AlterField(
            model_name='setting',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
