# Generated by Django 5.1.2 on 2024-11-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_setting_goal_alter_setting_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='term_length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
