# Generated by Django 5.1.3 on 2024-11-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_productdetails_term_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
