# Generated by Django 5.1.3 on 2024-11-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_first_name_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='email_address',
            new_name='email',
        ),
    ]
