# Generated by Django 5.1.2 on 2024-12-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_importantlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrate',
            name='interest_rate',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='minimum_deposit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
