# Generated by Django 5.1.2 on 2024-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_interestrate_interest_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLink',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_useful_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='popup',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
