# Generated by Django 5.1.2 on 2024-12-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_importantlink_sociallink_is_useful_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='childCustomers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='effective_date',
            field=models.CharField(max_length=155),
        ),
    ]
