# Generated by Django 5.1.2 on 2024-12-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_companyprofile_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_affiliation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
