# Generated by Django 5.1.2 on 2024-12-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_sociallink_is_active_sociallink_is_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='is_social_link',
            field=models.BooleanField(default=False),
        ),
    ]
